site_name: Music Apps Docs (Logger & Hunter)
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections

nav:
  - Home: index.md
  - Legal:
      - 'Privacy Policy': privacy-policy.md
      - 'AGB': agb.md
